
version: '3'

services:
  webapp:
    build: .
    ports:
      - "80:80"
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8081"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
