
version: '3'

services:
  webapp:
    build: .
    container_name: hydroponics-webapp
    image: hydro-parameter-viewer-webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - hydroponics-network
    depends_on:
      - websocket
    restart: unless-stopped
    # Improved healthcheck with longer timeouts for initial startup
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: hydroponics-websocket
    image: hydro-parameter-viewer-websocket
    ports:
      - "8081:8081"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./ssl:/etc/nginx/ssl
    environment:
      - USE_SSL=true  # Enable SSL for WebSocket
      - MOCK_DATA=true  # Use mock data for testing initially
    networks:
      - hydroponics-network
    restart: unless-stopped
    # Improved healthcheck for websocket service
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8081/health" , "||", "exit", "0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  hydroponics-network:
    driver: bridge
