
services:
  webapp:
    build: .
    container_name: hydroponics-webapp
    image: hydro-parameter-viewer-webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - hydroponics-network
    depends_on:
      - websocket
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: hydroponics-websocket
    image: hydro-parameter-viewer-websocket
    ports:
      - "8081:8081"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./logs:/app/logs
    environment:
      - USE_SSL=false  # Set to false to avoid SSL issues during debugging
      - MOCK_DATA=false  # Set to false to use real Arduino data
      - LOG_LEVEL=DEBUG  # Set log level to DEBUG for more detailed logs
      - SERIAL_PORT=/dev/ttyUSB0  # Set the serial port for the Arduino
      - BAUD_RATE=9600  # Set the baud rate for the Arduino
    networks:
      - hydroponics-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  hydroponics-network:
    driver: bridge
