
services:
  webapp:
    build: .
    container_name: hydroponics-webapp
    image: hydro-parameter-viewer-webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - hydroponics-network
    depends_on:
      - websocket
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: hydroponics-websocket
    image: hydro-parameter-viewer-websocket
    ports:
      - "8081:8081"
      - "8082:8082"  # Additional port for HTTP health checks
    # Make device mounting optional using variable substitution
    devices:
      - "${SERIAL_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./logs:/app/logs
    environment:
      - USE_SSL=true  # Set to true to use SSL
      - MOCK_DATA=${MOCK_DATA:-false}  # Changed default to false to prioritize real data
      - LOG_LEVEL=DEBUG  # Set log level to DEBUG for more detailed logs
      - SERIAL_PORT=/dev/ttyUSB0  # Set the serial port for the Arduino
      - BAUD_RATE=9600  # Set the baud rate for the Arduino
      - WS_PORT=8081  # Set the WebSocket port
    networks:
      - hydroponics-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  serial-monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: hydroponics-serial-monitor
    image: hydro-parameter-viewer-serial-monitor
    # Use the same Arduino device
    devices:
      - "${SERIAL_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0"
    environment:
      - SERIAL_PORT=/dev/ttyUSB0
      - BAUD_RATE=9600
      - MOCK_DATA=${MOCK_DATA:-false}  # Changed default to false to prioritize real data
      - MAX_RETRIES=5
      - RETRY_DELAY=3
    restart: unless-stopped
    # No need for network connection - this container just logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Add privilege setting for serial access
    privileged: true

networks:
  hydroponics-network:
    driver: bridge
