
version: '3'

services:
  webapp:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - hydroponics-network
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8081:8081"
    # Make device mounting optional
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./ssl:/etc/nginx/ssl
    environment:
      - USE_SSL=true
      - MOCK_DATA=true  # Enable mock data when USB device is unavailable
    networks:
      - hydroponics-network

networks:
  hydroponics-network:
    driver: bridge
