
services:
  webapp:
    build: .
    container_name: hydroponics-webapp
    image: hydro-parameter-viewer-webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./logs:/logs
    networks:
      - hydroponics-network
    depends_on:
      - serial-monitor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

  serial-monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: hydroponics-serial-monitor
    image: hydro-parameter-viewer-serial-monitor
    # Use the Arduino device
    devices:
      - "${SERIAL_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0"
    environment:
      - SERIAL_PORT=/dev/ttyUSB0
      - BAUD_RATE=9600
      - MOCK_DATA=${MOCK_DATA:-false}
      - MAX_RETRIES=5
      - RETRY_DELAY=3
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - hydroponics-network
    # Add privilege setting for serial access
    privileged: true
    # Define a healthcheck
    healthcheck:
      test: ["CMD", "grep", "-q", "Serial Monitor", "/app/logs/serial_monitor.log"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  hydroponics-network:
    driver: bridge
